version: '3.8'

services:
    kaiahub_email_server:
        image: analogic/poste.io
        container_name: kaiahub_email_server
        hostname: mail.kaiahub.ar
        restart: always
        networks:
            - dmit_network
        ports:
            - "25:25"
            - "110:110"
            - "143:143"
            - "465:465"
            - "587:587"
            - "993:993"
            - "995:995"
            - "4190:4190"
            - "8080:8080"
            - "4443:4443"
        environment:
            - TZ=America/New_York
            - h=mail.kaiahub.ar
            - EXPECTED_PROXY_ADDRESS=207.154.213.90
            - HTTP_PORT=8080
            - HTTPS_PORT=4443
            - HTTPS=OFF
            - DISABLE_CLAMAV=TRUE
            - DISABLE_RSPAMD=TRUE
        volumes:
            - /mnt/kaiahub_mail:/data

networks:
    dmit_network:
        external: true
